apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-persistentvolumeclaim
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 10GiB
  accessModes:
    - readWriteMany