apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  labels:
    name: prometheus-configmap
  namespace: observability-namespace
data:
  prometheus.yaml: |-
    global:
      scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    
    scrape_configs:
      - job_name: "prometheus"

        static_configs:
          - targets: ["localhost:9090"]
      
      - job_name: "sentinel"

        static_configs:
          - targets: ["10.43.1.100:2112"]
