---
# file: roles/common/tasks/main.yml
- name: System Stats
      debug:
        msg: |
          ipv4: {{ ansible_facts['default_ipv4']['address'] }}/{{ ansible_facts['default_ipv4']['prefix'] }} {{ ansible_facts['default_ipv4']['gateway'] }}
          os: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}
          volumes: {{ ansible_facts['lvm']['lvs'] }}
          python: {{ ansible_facts['python_version'] }}
          selinux: {{ ansible_facts['selinux']['config_mode'] }}
- name: Copy EPEl GPG key
  copy:
    src: RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
  when: ansible_facts['os_family'] == "RedHat"
- name: Import EPEL GPG key
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present
  when: ansible_facts['os_family'] == "RedHat"
- name: Install EPEL repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  when: ansible_facts['os_family'] == "RedHat"
- name: Ensure common packages
  dnf:
    name: "{{ item }}"
    state: installed
  loop: "{{ common_packages }}"
  when: ansible_facts['os_family'] == "RedHat"
- name: Ensure running common services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ common_services }}"
- name: Ensure common users
  user:
    name: "{{ item }}"
    state: present
  loop: "{{ common_users }}"
- name: Add authorized keys
  authorized_key:
    user: "{{ item }}"
    key: "{{ pubkey }}"
    state: present
  loop: "{{ common_users }}"