## package management
- name: Copy EPEl GPG key
  copy:
    src: RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
  when: ansible_facts['os_family'] == "RedHat"
- name: Import EPEL GPG key
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present
  when: ansible_facts['os_family'] == "RedHat"
- name: Install EPEL repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  when: ansible_facts['os_family'] == "RedHat"
- name: Ensure common packages
  dnf:
    name: "{{ item }}"
    state: installed
  loop: "{{ common_packages }}"
  when: ansible_facts['os_family'] == "RedHat"
