---
# file: roles/dnsmasq/tasks/main.yml
- name: Ensure dnsmasq package
  apt:
    name: dnsmasq
    state: latest
  register: dnspackage

- name: Dnsmasq config
  copy:
    src: ../dnsmasq/dnsmasq.conf 
    dest: /etc/dnsmasq.conf
  register: dnsconfig

- name: Restart dnsmasq
  systemd_service:
    name: dnsmasq.service
    daemon-reload: true
    state: restarted
    enabled: true
  when: dnsconfig is changed or dnspackage is changed

- name: Disable systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Ensure dnsmasq is running
  service:
    name: dnsmasq
    state: started
    enabled: true

- name: Open firewall
  become: yes
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  loop:
    - 53
    - 67
