---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  labels:
    name: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.211
    path: /nfs/prometheus

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  namespace: observability
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 10GiB
  accessModes:
    - ReadWriteMany

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  labels:
    name: prometheus
  namespace: observability
data:
  prometheus.yaml: |-
    global:
      scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    
    scrape_configs:
      - job_name: "prometheus"

        static_configs:
          - targets: ["localhost:9090"]
      
      - job_name: "sentinel"

        static_configs:
          - targets: ["10.43.1.100:2112"]
  
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: observability
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector: 
    app: prometheus
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 9090 
      nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: observability
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yaml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-configmap
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-configmap
          configMap:
            defaultMode: 420
            name: prometheus-configmap
        - name: prometheus-persistentvolume
          persistentVolumeClaim:
            claimName: prometheus-persistentvolumeclaim