---
# file: roles/hardening/tasks/main.yml
- name: Block non-required services
  firewalld:
    service: "{{ item }}"
    state: disabled
    permanent: yes
    immediate: yes
  loop:
    - dhcpv6-client
- name: Enable required services
  firewalld:
    service: ssh
    state: enabled
    permanent: yes
    immediate: yes
- name: Ensure SELinux is enabled and enforcing
  selinux:
    policy: targeted
    state: enforcing
  register: selinux_status
- name: Verify if reboot needed
  ansible.builtin.debug:
    msg: "Reboot needed: {{ selinux_status.reboot_required }}"
  changed_when: selinux_status.reboot_required | bool
  notify: reboot_host