---
# file: roles/kvm/tasks/main.yml
- name: Basic setup
  block: 
    - name: Ensure packages
      dnf:
        name: "{{ item }}"
        state: installed
      loop: "{{ packages }}"
      when: ansible_facts['os_family'] == "RedHat"
    - name: Enable cockpit socket
      systemd_service:
        name: cockpit.socket
        state: started
        enabled: true
    - name: Allow firewall access to cockpit
      firewalld:
        service: cockpit
        state: enabled
        permanent: yes
        immediate: yes
      when: ansible_facts['os_family'] == "RedHat"
- name: Setup virt services
  block:
    - name: Ensure sockets
      systemd_service:
        name: virt{{ item }}d.socket
        state: started
        enabled: true
      loop: "{{ sockets }}"
    - name: Ensure sockets -admin
      systemd_service:
        name: virt{{ item }}d-admin.socket
        state: started
        enabled: true
      loop: "{{ sockets }}"
    - name: Ensure sockets -ro
      systemd_service:
        name: virt{{ item }}d-ro.socket
        state: started
        enabled: true
      loop: "{{ sockets }}"
- name: Check virtual machines
  block:
    - name: Check VMs
      community.libvirt.virt:
        command: list_vms
      register: current_vms
    - name: List VMs
      debug:
        var: current_vms.list_vms
- name: Create virtual machines
  block:
    - name: Define VM
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('files', '{{ item }}.xml') }}"
      loop:
        - ansible1
        - ansible2
      when: "item not in current_vms.list_vms"
- name: Ensure VMs are running
  community.libvirt.virt:
    name: "{{ item }}"
    state: running
    autostart: true
  loop: "{{ required_vms }}"
