---
- name: Get install script
  hosts:
    - 192.168.1.205
  remote_user: ansible
  roles:
    - role: common
  tasks:
    - name: Get k3s installed version
      ansible.builtin.command: k3s --version
      register: k3s_version_output
      changed_when: false
      ignore_errors: true

    - name: Get install script
      when: k3s_version_output.rc != 0
      ansible.builtin.get_url:
        url: https://get.k3s.io/
        dest: /usr/local/bin/k3s-install.sh
        owner: root
        group: root
        mode: "0755"
    
    - name: Join cluster
      when: k3s_version_output.rc != 0
      ansible.builtin.shell:
        cmd: /usr/local/bin/k3s-install.sh agent --server=https://192.168.1.202:6443
      environment:
        K3S_TOKEN: "{{ K3S_TOKEN }}" 

      
