---
- name: Get export definititions
  hosts: localhost
  become: no
  vars_files:
    - ../nfs/exports.yaml
  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ exports }}"
    
- name: Bootstrap NFS server
  hosts:
  - 192.168.1.211
  remote_user: ansible
  vars_files:
    - ../nfs/exports.yaml
  roles:
    - common
  tasks:
    - name: Parition and format disk
      community.general.parted:
        device: /dev/sdb
        number: "{{ item.partition }}"
        label: gpt
        state: present
        fs_type: ext4 
        part_start: "{{ item.start }}"
        part_end: "{{ item.end }}"
      loop: "{{ exports }}"
    
    - name: Create a ext4 filesystem on /dev/sdbX
      community.general.filesystem:
        fstype: ext4
        dev: "/dev/sdb{{ item.partition }}"
      loop: "{{ exports }}"

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: "0644"
      loop: "{{ exports }}"
    
    - name: Mount volume
      ansible.posix.mount:
        path: "{{ item.path }}"
        src: "/dev/sdb{{ item.partition }}"
        fstype: ext4
        state: present
      loop: "{{ exports }}"
    
    - name: Install nfs-kernel-server
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present
    
    - name: Write config file
      ansible.builtin.template:
        src: nfs_exports_template.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: "0644"
    
    - name: Start service
      ansible.builtin.service:
        name: nfs-kernel-server
        enabled: yes
        state: restarted

    
